config/blobs.yml, packages/kubernetes-windows/packaging, packages/kubernetes-windows/spec
=> Upgrade kubernetes to v1.14.5 (#16)

config/blobs.yml, packages/kubernetes-windows/packaging, packages/kubernetes-windows/spec
This is an auto generated PR created for kubernetes upgrade to v1.14.10
=> kubernetes upgrade v1.14.10

jobs/kubelet-windows/spec, jobs/kubelet-windows/templates/bin/kubelet_ctl.ps1.erb, spec/kubelet_windows_ctl_spec.rb
This changes ports the TLS fixes into the 1.6. branch.
=> Port TLS fixes into 1.6

jobs/kubelet-windows/spec, jobs/kubelet-windows/templates/bin/kubelet_ctl.ps1.erb, jobs/kubelet-windows/templates/bin/post-start.ps1, jobs/kubelet-windows/templates/bin/pre-start.ps1, jobs/kubelet-windows/templates/config/file-arguments.json.erb
Update kubelet-windows job to support file arguments.
=> Update kubelet-windows to support file arguments

config/blobs.yml, packages/kubernetes-windows/packaging, packages/kubernetes-windows/spec
This is an auto generated PR created for kubernetes upgrade to 1.16.7
=> kubernetes upgrade 1.16.7

config/blobs.yml, packages/kubernetes-windows/packaging, packages/kubernetes-windows/spec
This is an auto generated PR created for kubernetes upgrade to 1.15.10
=> bump kubernetes to 1.15.10

config/blobs.yml, jobs/flanneld-windows/templates/bin/flanneld_ctl.ps1.erb, packages/kubernetes-windows/packaging, packages/kubernetes-windows/spec, run_tests.sh
This is an auto generated PR created for kubernetes upgrade to 1.17.3
=> kubernetes upgrade 1.17.3

config/blobs.yml, packages/kubernetes-windows/packaging, packages/kubernetes-windows/spec
This is an auto generated PR created for kubernetes upgrade to 1.16.10
=> bump kubernetes to 1.16.10

config/blobs.yml, packages/kubernetes-windows/packaging, packages/kubernetes-windows/spec
This is an auto generated PR created for kubernetes upgrade to 1.18.3
=> bump kubernetes to 1.18.3

config/blobs.yml, packages/kubernetes-windows/packaging, packages/kubernetes-windows/spec
Reverts pivotal-cf/pks-kubernetes-windows-release#44
=> Revert "bump kubernetes to 1.18.3"

README.md, jobs/kube-proxy-windows/spec, jobs/kubelet-windows/spec, jobs/kubo-dns-aliases/templates/dns/aliases.json.erb
=> Fix language

.final_builds/packages/docker-windows/index.yml, .final_builds/packages/kubernetes-windows/index.yml, config/blobs.yml, packages/kubernetes-windows/packaging, packages/kubernetes-windows/spec, releases/kubo-windows/index.yml, releases/kubo-windows/kubo-windows-1.8.0-build.24-bump-kubernetes-1.17.11.yml
This is an auto generated PR created for kubernetes upgrade to 1.17.11
=> bump kubernetes to 1.17.11

jobs/kubelet-windows/templates/bin/drain.ps1.erb
Cherry pick https://github.com/pivotal-cf/pks-kubernetes-windows-release/pull/69
=> Add watch disk in drain

jobs/kubelet-windows/templates/bin/drain.ps1.erb
=> Fix the flag name

config/blobs.yml, packages/kubernetes-windows/packaging, packages/kubernetes-windows/spec
This is an auto generated PR created for kubernetes upgrade to 1.17.13
=> bump kubernetes to 1.17.13

jobs/kubelet-windows/templates/bin/kubelet_ctl.ps1.erb
Fix https://jira.eng.vmware.com/browse/PKS-3373
PKS Pipeline: https://pks.ci.cf-app.com/teams/dev/pipelines/pks-api-1.10-persist-node-label-taints
RaaS pipeline: https://raas.gcp.pks-releng.cf-app.com/teams/od-pks/pipelines/vsphere67-nsx25-om210-install-linux-persist-node-label-taints
I also manually verified the functionality.
=> Set node labels & taints for kubelet

config/blobs.yml, packages/kubernetes-windows/packaging, packages/kubernetes-windows/spec
This is an auto generated PR created for kubernetes upgrade to 1.19.4
=> bump kubernetes to 1.19.4

config/blobs.yml, packages/kubernetes-windows/packaging, packages/kubernetes-windows/spec
This is an auto generated PR created for kubernetes upgrade to 1.16.15
=> bump kubernetes to 1.16.15

config/blobs.yml, packages/kubernetes-windows/packaging, packages/kubernetes-windows/spec
This is an auto generated PR created for kubernetes upgrade to 1.18.14
=> bump kubernetes to 1.18.14

config/blobs.yml, packages/kubernetes-windows/packaging, packages/kubernetes-windows/spec
This is an auto generated PR created for kubernetes upgrade to 1.17.17
=> bump kubernetes to 1.17.17

config/blobs.yml, packages/kubernetes-windows/packaging, packages/kubernetes-windows/spec
This is an auto generated PR created for kubernetes upgrade to 1.19.9
=> bump kubernetes to 1.19.9

.final_builds/jobs/docker-windows/index.yml, jobs/docker-windows/templates/bin/pre-start.ps1, jobs/docker-windows/templates/config/daemon.json.erb, releases/kubo-windows/index.yml, releases/kubo-windows/kubo-windows-1.11.0-build.8-change-docker-rootdir.yml
see https://vmware.slack.com/archives/C3M0B3TV3/p1618983905244000
fix https://pivotal-spike.atlassian.net/browse/PKS-1079
manually test result
```
PS C:\Users\bosh_7b2f15c73b6d4fc> docker.exe info
Client:
Debug Mode: false
Server:
Containers: 0
Running: 0
Paused: 0
Stopped: 0
Images: 0
Server Version: 19.03.14
Storage Driver: windowsfilter
Windows:
Logging Driver: json-file
Plugins:
Volume: local
Network: ics internal l2bridge l2tunnel nat null overlay private transparent
Log: awslogs etwlogs fluentd gcplogs gelf json-file local logentries splunk syslog
Swarm: inactive
Default Isolation: process
Operating System: Windows Server 2019 Datacenter Evaluation Version 1809 (OS Build 17763.737)
OSType: windows
Architecture: x86_64
CPUs: 2
Total Memory: 8GiB
Name: …
```
=> Change docker root directory to ephemeral disk

config/blobs.yml, packages/kubernetes-windows/packaging, packages/kubernetes-windows/spec
This is an auto generated PR created for kubernetes upgrade to 1.19.10
=> bump kubernetes to 1.19.10

config/blobs.yml, packages/kubernetes-windows/packaging, packages/kubernetes-windows/spec
This is an auto generated PR created for kubernetes upgrade to 1.20.6
=> bump kubernetes to 1.20.6

jobs/drain-cluster-windows/spec, jobs/drain-cluster-windows/templates/bin/run.ps1
add drain-cluster job for windows
=> fix pks-4072 windows drain cluster

config/blobs.yml, packages/kubernetes-windows/packaging, packages/kubernetes-windows/spec
This is an auto generated PR created for kubernetes upgrade to 1.21.1
=> bump kubernetes to 1.21.1

config/blobs.yml, packages/kubernetes-windows/packaging, packages/kubernetes-windows/spec
This is an auto generated PR created for kubernetes upgrade to 1.20.8
=> bump kubernetes to 1.20.8

config/blobs.yml, packages/kubernetes-windows/packaging, packages/kubernetes-windows/spec
This is an auto generated PR created for kubernetes upgrade to 1.19.13
=> bump kubernetes to 1.19.13
